CBM_DEFAULTS = {
    "cbm_pfi_enable": False,
    "cbm_start_epoch": 0,
    "cbm_memory_dim": 128,
    "cbm_value_dim": 8,
    "cbm_labeled_memory_profile": "auto",
    "cbm_labeled_memory_profile_overrides": {},
    "cbm_labeled_split": None,
    "cbm_memory_finalize_strategy": "image_balanced_reliability_diversity",
    "cbm_memory_sample_per_image_labeled": {
        "fg_core": 128,
        "fg_boundary": 384,
        "bg_near": 384,
        "bg_far": 128,
    },
    "cbm_memory_max_sizes": {
        "fg_core": 8192,
        "fg_boundary": 16384,
        "bg_near": 16384,
        "bg_far": 8192,
    },
    "cbm_memory_grid_size": 4,
    "cbm_memory_min_tokens_per_component": {
        "fg_core": 2,
        "fg_boundary": 4,
        "bg_near": 4,
        "bg_far": 2,
    },
    "cbm_memory_min_spatial_dist": {
        "fg_core": 2,
        "fg_boundary": 2,
        "bg_near": 2,
        "bg_far": 3,
    },
    "cbm_memory_grid_quota_ratio": {
        "fg_core": 0.35,
        "fg_boundary": 0.20,
        "bg_near": 0.20,
        "bg_far": 0.15,
    },
    "cbm_memory_max_feature_sim": 0.98,
    "cbm_memory_use_component_quota": True,
    "cbm_memory_use_grid_quota": True,
    "cbm_memory_use_spatial_diversity": True,
    "cbm_memory_use_feature_diversity": True,
    "cbm_memory_relax_diversity_if_underfilled": True,
    "cbm_memory_relaxed_min_spatial_dist": 1,
    "cbm_memory_relaxed_max_feature_sim": 0.995,
    "cbm_memory_allow_underfill": True,
    "cbm_memory_global_fill_max_per_image": None,
    "cbm_memory_vis_enable": True,
    "cbm_memory_vis_max_images": 5,
    "cbm_memory_vis_seed": 0,
    "cbm_memory_vis_dir": None,
    "cbm_top_img_k": 8,
    "cbm_topk_token": 16,
    "cbm_lambda_feat": 0.1,
    "cbm_lambda_logit": 0.5,
    "cbm_boundary_kernel": 3,
    "cbm_boundary_alpha_unc": 0.5,
    "cbm_boundary_alpha_grad": 0.5,
    "cbm_boundary_theta": 0.2,
    "cbm_context_kernel_size": 3,
    "cbm_context_tau_feat": 0.1,
    "cbm_context_tau_prob": 0.2,
    "cbm_context_tau_evi": 0.2,
    "cbm_lambda_mem": 0.2,
    "cbm_lambda_bd": 0.2,
    "cbm_lambda_ctx": 0.05,
    "cbm_lambda_aff": 0.05,
    "cbm_lambda_gate_sparse": 0.01,
    "cbm_lambda_gate_boundary": 0.05,
    "cbm_boundary_margin": 0.2,
    "cbm_affinity_kernel_size": 3,
    "cbm_loss_eps": 1e-6,
    "cbm_stage_epoch_offset": 1,
    "cbm_stage1_end": 5,
    "cbm_stage2_end": 15,
    "cbm_unlabeled_start_epoch": 16,
    "cbm_unsup_loss_alpha": 0.1,
    "cbm_checkpoint_memory": True,
    "cbm_vis_enable": False,
    "cbm_vis_interval": 200,
    "cbm_vis_max_images": 2,
    "cbm_vis_dir": None,
    "cbm_vis_labeled_only": True,
}

for _cbm_key, _cbm_value in CBM_DEFAULTS.items():
    locals()[_cbm_key] = _cbm_value
del _cbm_key, _cbm_value
