PC_HBM_DEFAULTS = {
    "use_pc_hbm": False,
    "pc_hbm_enable": False,
    "memory_source": "labeled_only",
    "memory_rebuild_interval": 1,
    "use_unlabeled_memory_update": False,
    "cbm_memory_dim": 512,
    "cbm_value_dim": 8,
    "geometry_dim": 6,
    "cbm_memory_feature_version": "swin_l_pc_hbm_v1",
    "cbm_top_img_k": 32,
    "parent_topk": 64,
    "cbm_tau_parent": 0.07,
    "cbm_tau_child": 0.10,
    "cbm_tau_hca": 0.10,
    "cbm_tau_bra": 0.10,
    "cbm_tau_pra": 0.10,
    "use_camouflage_context_router": True,
    "use_multi_hypothesis_parent": True,
    "parent_group_mode": "four_region",
    "use_child_verifier": True,
    "child_window_size": 5,
    "use_geometry_value": True,
    "use_structured_prior_bias_net": True,
    "use_hyp_score_net": True,
    "use_structured_gate_mlp": True,
    "use_boundary_query_head": True,
    "use_pc_hca": True,
    "use_p2_bra": True,
    "use_p1_pra": True,
    "attn_num_heads": 8,
    "attn_head_dim": 64,
    "p2_bra_local_window": 3,
    "p1_pra_local_window": 3,
    "p2_boundary_top_ratio": 0.25,
    "p1_boundary_top_ratio": 0.20,
    "use_adaptive_mixture": True,
    "mixture_branches": ["keep", "residual", "deformation", "suppress"],
    "mixture_init_bias": [1.0, -0.5, -0.5, -0.5],
    "mixture_eps_start": 0.10,
    "mixture_eps_end": 0.00,
    "mixture_eps_decay_epoch": 10,
    "mixture_temperature_start": 1.5,
    "mixture_temperature_end": 0.8,
    "use_branch_oracle_supervision": True,
    "use_branch_quality_head": True,
    "use_conditional_usage_loss": True,
    "use_branch_dropout": True,
    "use_suppress_head": True,
    "use_mask_corr_head": False,
    "mask_corr_epsilon": 0.10,
    "r_max": 2.0,
    "max_offset": 3.0,
    "lambda_final": 1.0,
    "lambda_main": 1.0,
    "lambda_nomix": 0.5,
    "lambda_mem": 0.2,
    "lambda_boundary_aux": 0.2,
    "lambda_mix_oracle": 0.2,
    "lambda_branch": 0.2,
    "lambda_quality": 0.05,
    "lambda_usage": 0.02,
    "lambda_reg": 0.05,
    "lambda_u": 1.0,
    "use_hard_teacher_loss": True,
    "hard_teacher_loss_weight": 2.0,
    "hard_teacher_threshold": 0.5,
    "use_soft_teacher_weighted_iou": True,
    "soft_teacher_weighted_iou_weight": 0.25,
    "warmup_epoch": 5,
    "parent_start_epoch": 6,
    "child_start_epoch": 11,
    "attention_refine_start_epoch": 11,
    "unlabeled_start_epoch": 16,
    "pc_hbm_detach_refs": True,
    "pc_hbm_unsup_final_consistency_weight": 0.1,
    "pc_hbm_tau_oracle": 0.5,
    "pc_hbm_checkpoint_memory": True,
    
    "p3_boundary_max_tokens" : 600,
    "p2_boundary_max_tokens" : 1200,
    "p1_boundary_max_tokens" : 2500,
    "p3_boundary_min_tokens" : 64,
    "p2_boundary_min_tokens" : 128,
    "p1_boundary_min_tokens" : 256,


}

for _pc_hbm_key, _pc_hbm_value in PC_HBM_DEFAULTS.items():
    locals()[_pc_hbm_key] = _pc_hbm_value
del _pc_hbm_key, _pc_hbm_value
